name: Build Image using Containerfile
on: [push]

env:
    REGISTRY: ghcr.io/${{ github.repository_owner }}
    REGISTRY_USER: ${{ github.actor }}
    REGISTRY_PASSWORD: ${{ github.token }}

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: ghcr.io/vodofrede/minecraft
        tags: latest ${{ github.sha }}
        containerfiles: |
          ./minecraft/Containerfile
        oci: true
    - name: Push to registry
      id: push-image
      uses: redhat-actions/push-to-registry@v2
      with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          extra-args: |
            --disable-content-trust
